<table class="col my-5 table table-striped">
    <thead>
        <tr>
            <th>
                #
            </th>
            <th>
                Nom d'utilisateur
            </th>
            <th>
                Email
            </th>
            <th>
                Mot de passe
            </th>
            <th>
                Rôle
            </th>
            <th>
                Date de création
            </th>
            <th>
                Supprimer
            </th>
        </tr>
    </thead>
    <tbody>
        <?php
        $userManager = new UserManager;
        $users = $userManager->findAll();
        foreach ($users as $user) {
        ?>
            <tr>
                <td> <?= $user['id'] ?> </td>
                <td> <?= $user['username'] ?> </td>
                <td> <?= $user['email'] ?> </td>
                <td> <?= $user['password'] ?> </td>
                <td> <?= $user['role'] ?> </td>
                <td> <?= $user['created_at'] ?> </td>

                <td>
                    <a href="logic/delete-user.php?id=<?= $user['id'] ?>" class="btn btn-danger">
                        <scan class="bi-trash-fill"></scan>
                    </a>
                </td>
            </tr>
        <?php
        };
        ?>
    </tbody>
    <tfoot>
        <tr>
            <th>
                #
            </th>
            <th>
                Nom d'utilisateur
            </th>
            <th>
                Email
            </th>
            <th>
                Mot de passe
            </th>
            <th>
                Rôle
            </th>
            <th>
                Date de création
            </th>
            <th>
                Supprimer
            </th>
        </tr>
    </tfoot>
</table>