<h2>Users</h2>
<form action="logic/add-user.php" method="post">
    <label for="userId">ID</label>
    <input type="number" name="userId" id="userId" required>
    <label for="username">Username</label>
    <input type="text" name="username" id="username" required>
    <label for="email">Email</label>
    <input type="email" name="email" id="email" required>
    <label for="password">Password</label>
    <input type="password" name="password" id="password" required>
    <label for="role">role</label>
    <input type="text" name="role" id="role" required>
    <label for="createdAt">Created at</label>
    <input type="datetime-local" name="createdAt" id="createdAt" required>
    <button type="submit">Add new User</button>
</form>

<?php require "users-list.phtml" ?>
<p>End</p>